.\" Manpage for arxunpak.
.\" Go to http://arx.vg/bug to correct errors or typos.
.TH arxunpak 1 "2013-06-28" "1.1"
.SH NAME
arxunpak \- Extract the Arx Fatalis .pak files containing the game assets
.SH SYNOPSIS
.B arxunpak
.I <pakfile>
[\fI<pakfile>\fP...]
.SH DESCRIPTION
.B arxunpak
extracts the .pak files containing the game assets of the original \fBArx Fatalis\fP.

This is not required to run \fBArx Libertatis\fP but can be useful for development.

All arguments are interpreted as files to extract.

Output files are written to the current working directory.
.SH SEE ALSO
\fBarx\fP(6), \fBarxsavetool\fP(1)
.SH BUGS
No known bugs.
