.\" Manpage for arxunpak.
.\" Go to https://bugs.arx-libertatis.org/ to correct errors or typos.
.TH arxunpak 1 "2012-03-28" "1.0"
.SH NAME
arxunpak \- Tool to extract the Arx Fatalis .pak files containing the game assets
.SH SYNOPSIS
.B arxunpak <pakfile> [<pakfile>...]
.SH DESCRIPTION
.B arxunpak
extracts the .pak files containing the game assets of the original 
.B Arx Fatalis
\&.

This is not required to run 
.B Arx Libertatis
but can be useful for development.

All arguments are interpreted as files to extract.

Output files are written to the current working directory.
.SH SEE ALSO
arx(6), arxsavetool(1)
.SH BUGS
No known bugs.
