#!/bin/sh

function die() {
	echo "$@" >&2
	exit 1
}

[ "$1" == "--help" ] || [ "$1" == "-h" ] || zipfile="$(readlink -f "$1")"
[ "$zipfile" != "" ] || die "Usage: install-demo path/to/arx_demo_english.zip [output_dir]"

if [ "$2" == "" ]
	then destdir="$(pwd)"
	else destdir="$(readlink -f "$2")"
fi

cd "$(dirname "$0")"
here="$(pwd)"

echo "Installing Arx Fatalis demo data from \"$zipfile\" to \"$destdir\"."
echo

cabextract=`which cabextract 2> /dev/null`
unzip=`which unzip 2> /dev/null`
bsdtar=`which bsdtar 2> /dev/null`
md5sum=`which md5sum 2> /dev/null`

[ -f "$cabextract" ] \
	|| die "Please install cabextract (http://www.cabextract.org.uk/)"

[ -f "$unzip" ] || [ -f "$bsdtar" ] \
	|| die "Please install unzip (http://www.info-zip.org/)" \
	       "or bsdtar from libarchive (http://libarchive.github.com/)"

[ -f "$zipfile" ] || die "Input file \"$zipfile\" not found."

function extract_cab() {
	"$cabextract" "$1"
}

function extract_zip() {
	if [ -f "$unzip" ]
		then "$unzip" "$1"
		else "$bsdtar" xvf "$1"
	fi
}

if [ -f "$md5sum" ]
	then 
		checksum="$(md5sum "$zipfile" | sed 's/ .*//')"
		expected='3c59a5799e1237b1b181c96e8c09155a'
		if [ "$checksum" == "$expected" ] 
			then echo "Checksum matched."
			else echo "Got checksum $checksum, expected $expected."
		fi
	else echo "Missing md5sum, cannot verify that you have the correct archive."
fi

mkdir -p "$destdir" || exit 1

tempdir="$destdir/arx-install-demo-temp"

rm -rf "$tempdir" 2> /dev/null
mkdir "$tempdir" || exit 1
cd "$tempdir" || exit 1

extract_zip "$zipfile"

extract_cab Setup1.cab
extract_cab Setup2.cab
extract_cab Setup3.cab

function doinstall() {
	mv -fv "$tempdir/$1" "$destdir/$2"
	chmod "--reference=$destdir" "$destdir/$2" &> /dev/null
	chmod -x "$destdir/$2" &> /dev/null
}

mkdir -pv "$destdir/misc"
doinstall "bin/Arx.ttf" "misc/arx.ttf"
doinstall "bin/Logo.bmp" "misc/logo.bmp"
doinstall "bin/data2.pak" "data2.pak"
doinstall "bin/LOC.pak" "loc.pak"
doinstall "data.pak" "data.pak"
doinstall "SFX.pak" "sfx.pak"
doinstall "SPEECH.pak" "speech.pak"

rm -rf "$tempdir"

echo
echo "Done:"

checksums_demo="$(cat "$here/data-demo.md5")"

if [ -f "$md5sum" ]
	then
		checksums=`cd "$destdir" \
			&& "$md5sum" data2.pak data.pak loc.pak misc/arx.ttf misc/logo.bmp sfx.pak speech.pak`
		if [ "$checksums" == "$checksums_demo" ]
			then echo "Checksum match."
			else
				echo >&2
				echo "Checksum mismatch, expected" >&2
				echo >&2
				echo "$checksums_demo" >&2
				echo >&2
				echo " got" >&2
				echo >&2
				echo "$checksums" >&2
				exit 1
		fi
	else
		echo "Could not verify checksum, md5 not available."
fi
