#!/bin/sh

# Checksums of speech*.pak used to detect languages.

speech_checksum_de="4c3fdb1f702700255924afde49081b6e"
speech_checksum_en="4e8f962d8204bcfd79ce6f3226d6d6de"
speech_checksum_es="2f88c67ae1537919e69386d27583125b"
speech_checksum_fr="4edf9f8c799190590b4cd52cfa5f91b1"
speech_checksum_it="81f05dea47c52d43f01c9b44dd8fe962"
speech_checksum_ru="677163bc319cd1e9aa1b53b5fb3e9402"

# Common checksums

checksums_common="\
f7e0ce700bf963429ac535ca86f8a7b4  data2.pak
afff1099c01ffeb03b9a351f7b5966b6  graph/interface/misc/arkane.bmp
41445d3792a1f8818d950aca47254488  graph/interface/misc/quit1.bmp
8419274acbff7346c3661b18d6aad6dc  graph/obj3d/textures/fixinter_barrel.jpg
5743b9047c9ad65540c318dfcc98123a  graph/obj3d/textures/fixinter_bell.bmp
f246eff6b19c9c710313b4a4dce96a69  graph/obj3d/textures/fixinter_metal_door.jpg
f81394abbb9006ce0950843b7909db33  graph/obj3d/textures/fixinter_public_notice.bmp
544448f8eedc912aa231a6a04fffb7c5  graph/obj3d/textures/item_bread.bmp
7e26c4199ddaca494c8b369294306b0b  graph/obj3d/textures/item_club.jpg
3a6196fe9b7666c7d80d82be06f6de86  graph/obj3d/textures/item_long_sword.jpg
18492c25ebac02f83e2f0ebda61ecb00  graph/obj3d/textures/item_mauld_sabre.jpg
503a5c2f23668040c675aefdde6dbbe5  graph/obj3d/textures/item_mauldsword.jpg
c0a22b4f7a7a6461da68206e94928637  graph/obj3d/textures/item_mirror.jpg
348f9add709bacee08556d1f8cf10f3f  graph/obj3d/textures/item_ring_casting.bmp
ff05de281c8b380ee98f6e123d3d51cb  graph/obj3d/textures/item_rope.bmp
024ccbb520020f92fba5a5a4f0270cea  graph/obj3d/textures/item_spell_sheet.jpg
027951899b4829599ca611010ea3484f  graph/obj3d/textures/item_torch2.jpg
9ada166f23ddcb775ac20836e752187e  graph/obj3d/textures/item_torch.jpg
cd206a4027f86c6e57b7710c94049efa  graph/obj3d/textures/item_zohark.bmp
79ccc81adb7c37b98f40b478ef1fccd4  graph/obj3d/textures/l7_dwarf_[wood]_board08.jpg
691611087b13d38ef02bb9dfd6a2518e  graph/obj3d/textures/l7_dwarf_[wood]_board80.jpg
116bd374c14ae8c387a4da1899e1dca7  graph/obj3d/textures/npc_dog.bmp
b7a4d0d3d230b2d1470176909004e38b  graph/obj3d/textures/npc_pig.bmp
76034d8d74056c8a982479d36321c228  graph/obj3d/textures/npc_pig_dirty.bmp
00c585ec9ebe8006d7ca72993de7b51b  graph/obj3d/textures/npc_rat_base.bmp
cae38facbf77db742180b9e58d0eb42f  graph/obj3d/textures/npc_rat_base_cm.bmp
0b220bffaedc89fa663f08d12630c342  graph/obj3d/textures/npc_worm_body_part1.jpg
20797cb78f6393a0fb5405969ba9f805  graph/obj3d/textures/npc_worm_body_part2.bmp
00d0b018e995e7d013d6e52e92126901  graph/obj3d/textures/[wood]_light_door.jpg
7a6038e0397e2319aea5d8dc408d5da8  manual.pdf
3502c76227df6bbd8637d5355e270cc2  map.pdf
9a95ff96795c034524ba1c2e94ea12c7  misc/arx_default.ttf
921561e83786efcd25f92147b60a13db  misc/arx_russian.ttf
da59198061cef0761c6b2fca113f76f6  misc/arx_taiwanese.ttf
63ed31a4eb3d226c23e58cfaa974d484  misc/logo.avi
afff1099c01ffeb03b9a351f7b5966b6  misc/logo.bmp
2efc9a74c517fd1ee9919900cf4091d2  sfx.pak"

# Language-specific checksums

data_checksum_common="a91a0b39a046233debbb10b4850e13eb  data.pak"
data_checksum_europe="a88d239dc7919ab113ff45483cb4ad46  data.pak"

checksums_de="${checksums_common}
${data_checksum_europe}
31bc35bca48e430e108db1b8bcc2621d  loc.pak
${speech_checksum_de}  speech.pak"

checksums_en="${checksums_common}
${data_checksum_common}
a47b192493afb5794e2161a62d35b69f  loc.pak
${speech_checksum_en}  speech.pak"

checksums_es="${checksums_common}
${data_checksum_common}
121f99608814a2c9c5857cfadb665553  loc.pak
${speech_checksum_es}  speech.pak"

checksums_fr="${checksums_common}
${data_checksum_common}
f8fc448fea12469ed94f417c313fe5ea  loc.pak
${speech_checksum_fr}  speech.pak"

checksums_it="${checksums_common}
${data_checksum_europe}
a9e162f2916f5737a95bd8c5bd8a979e  loc.pak
${speech_checksum_it}  speech.pak"

checksums_ru="${checksums_common}
${data_checksum_europe}
a131bf2398ee70a9c22a2bbffd9d0d99  loc.pak
${speech_checksum_ru}  speech.pak"

# List of required files

set -- \
	"data2.pak" \
	"graph/interface/misc/arkane.bmp" \
	"graph/interface/misc/quit1.bmp" \
	"graph/obj3d/textures/fixinter_barrel.jpg" \
	"graph/obj3d/textures/fixinter_bell.bmp" \
	"graph/obj3d/textures/fixinter_metal_door.jpg" \
	"graph/obj3d/textures/fixinter_public_notice.bmp" \
	"graph/obj3d/textures/item_bread.bmp" \
	"graph/obj3d/textures/item_club.jpg" \
	"graph/obj3d/textures/item_long_sword.jpg" \
	"graph/obj3d/textures/item_mauld_sabre.jpg" \
	"graph/obj3d/textures/item_mauldsword.jpg" \
	"graph/obj3d/textures/item_mirror.jpg" \
	"graph/obj3d/textures/item_ring_casting.bmp" \
	"graph/obj3d/textures/item_rope.bmp" \
	"graph/obj3d/textures/item_spell_sheet.jpg" \
	"graph/obj3d/textures/item_torch2.jpg" \
	"graph/obj3d/textures/item_torch.jpg" \
	"graph/obj3d/textures/item_zohark.bmp" \
	"graph/obj3d/textures/l7_dwarf_[wood]_board08.jpg" \
	"graph/obj3d/textures/l7_dwarf_[wood]_board80.jpg" \
	"graph/obj3d/textures/npc_dog.bmp" \
	"graph/obj3d/textures/npc_pig.bmp" \
	"graph/obj3d/textures/npc_pig_dirty.bmp" \
	"graph/obj3d/textures/npc_rat_base.bmp" \
	"graph/obj3d/textures/npc_rat_base_cm.bmp" \
	"graph/obj3d/textures/npc_worm_body_part1.jpg" \
	"graph/obj3d/textures/npc_worm_body_part2.bmp" \
	"graph/obj3d/textures/[wood]_light_door.jpg" \
	"manual.pdf" \
	"map.pdf" \
	"misc/arx_default.ttf" \
	"misc/arx_russian.ttf" \
	"misc/arx_taiwanese.ttf" \
	"misc/logo.avi" \
	"misc/logo.bmp" \
	"sfx.pak" \
	"data.pak" \
	"loc.pak" \
	"speech.pak"

# Common functions

md5sum=`which md5sum 2> /dev/null`
[ -f "$md5sum" ] \
	|| die "Please install md5sum (http://www.gnu.org/software/coreutils/)"

expected_checksums="$checksums_en"
detect_language() {
	
	langdir="$1"
	
	speech_checksum=`find "$langdir" -iname "speech*.pak" -exec "$md5sum" {} \; | sed "s/ .*//g"`
	
	case "$speech_checksum" in
		"$speech_checksum_de") data_lang='german'  ; expected_checksums="$checksums_de" ;;
		"$speech_checksum_en") data_lang='english' ; expected_checksums="$checksums_en" ;;
		"$speech_checksum_es") data_lang='spanish' ; expected_checksums="$checksums_es" ;;
		"$speech_checksum_fr") data_lang='french'  ; expected_checksums="$checksums_fr" ;;
		"$speech_checksum_it") data_lang='italian' ; expected_checksums="$checksums_it" ;;
		"$speech_checksum_ru") data_lang='russian' ; expected_checksums="$checksums_ru" ;;
		'') die "speech*.pak not found in $source" ;;
		*) die "unsupported data language - speech*.pak checksum: $speech_checksum" ;;
	esac
	
	echo "
Data language: $data_lang
"
}

verify_checksums() {
	
	echo "
Done:"
	
	checkdir="$1" ; shift
	
	checksums=`cd "$checkdir" && "$md5sum" "$@" 2> /dev/null`
	
	[ "$checksums" = "$expected_checksums" ] || die "
Checksum mismatch, expected

$expected_checksums

 got

$checksums

ERROR: Checksum mismatch."
	
echo "Checksum match."
}
